sudo: required
language: node_js
node_js:
  - "node"
before_script:
  - cd test
  - npm install
  - npm install -g mocha
services:
    - docker
script:
 - docker-compose -f ../caMicroscope.yml build
 - docker-compose -f ../caMicroscope.yml up -d
 - sleep 30
- mocha *.js --exit
